/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaketRouteImport } from './routes/paket'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TryoutSesiIdRouteImport } from './routes/tryout.$sesiId'
import { Route as HasilSesiIdRouteImport } from './routes/hasil.$sesiId'
import { Route as BayarPaketIdRouteImport } from './routes/bayar.$paketId'

const PaketRoute = PaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TryoutSesiIdRoute = TryoutSesiIdRouteImport.update({
  id: '/tryout/$sesiId',
  path: '/tryout/$sesiId',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilSesiIdRoute = HasilSesiIdRouteImport.update({
  id: '/hasil/$sesiId',
  path: '/hasil/$sesiId',
  getParentRoute: () => rootRouteImport,
} as any)
const BayarPaketIdRoute = BayarPaketIdRouteImport.update({
  id: '/bayar/$paketId',
  path: '/bayar/$paketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/paket': typeof PaketRoute
  '/bayar/$paketId': typeof BayarPaketIdRoute
  '/hasil/$sesiId': typeof HasilSesiIdRoute
  '/tryout/$sesiId': typeof TryoutSesiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/paket': typeof PaketRoute
  '/bayar/$paketId': typeof BayarPaketIdRoute
  '/hasil/$sesiId': typeof HasilSesiIdRoute
  '/tryout/$sesiId': typeof TryoutSesiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/paket': typeof PaketRoute
  '/bayar/$paketId': typeof BayarPaketIdRoute
  '/hasil/$sesiId': typeof HasilSesiIdRoute
  '/tryout/$sesiId': typeof TryoutSesiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/paket'
    | '/bayar/$paketId'
    | '/hasil/$sesiId'
    | '/tryout/$sesiId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/paket'
    | '/bayar/$paketId'
    | '/hasil/$sesiId'
    | '/tryout/$sesiId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/paket'
    | '/bayar/$paketId'
    | '/hasil/$sesiId'
    | '/tryout/$sesiId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PaketRoute: typeof PaketRoute
  BayarPaketIdRoute: typeof BayarPaketIdRoute
  HasilSesiIdRoute: typeof HasilSesiIdRoute
  TryoutSesiIdRoute: typeof TryoutSesiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paket': {
      id: '/paket'
      path: '/paket'
      fullPath: '/paket'
      preLoaderRoute: typeof PaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tryout/$sesiId': {
      id: '/tryout/$sesiId'
      path: '/tryout/$sesiId'
      fullPath: '/tryout/$sesiId'
      preLoaderRoute: typeof TryoutSesiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil/$sesiId': {
      id: '/hasil/$sesiId'
      path: '/hasil/$sesiId'
      fullPath: '/hasil/$sesiId'
      preLoaderRoute: typeof HasilSesiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bayar/$paketId': {
      id: '/bayar/$paketId'
      path: '/bayar/$paketId'
      fullPath: '/bayar/$paketId'
      preLoaderRoute: typeof BayarPaketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PaketRoute: PaketRoute,
  BayarPaketIdRoute: BayarPaketIdRoute,
  HasilSesiIdRoute: HasilSesiIdRoute,
  TryoutSesiIdRoute: TryoutSesiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
